---
- name: Ensure Repo Is Absent
  file:
    path: /etc/yum.repos.d/docker-ce-stable.repo
    state:  absent

- name: Add A Docker Repository
  yum_repository:
      name: docker-ce-stable
      description: "Docker CE Stable - $basearch"
      baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
      gpgcheck: true
      gpgkey: "https://download.docker.com/linux/centos/gpg"
      enabled: true
  when: ansible_os_family == "RedHat"


    
