---
- name: Install Docker
  dnf:
    name: "{{ item  }}"
    state:  present
  loop: "{{ docker_pkg  }}"
  notify: Started Docker Service
  when: ansible_os_family == "RedHat"


- name: Add User To A Docker Group
  user:
    name: "{{ docker_user  }}"
    groups: docker
    append: yes
  when: docker_user != " "

          
