---
- name: Update The Target Server
  dnf:
    update_cache: yes
  changed_when: yes
  when: ansible_os_family == "RedHat"

- name: Remove The Old Packages For Docker If Exist
  dnf:
    name: "{{ item  }}"
    state:  absent
  loop: "{{ remove_pkg }}"
  when: ansible_os_family == "RedHat"

- name: Remove Unnecessary Packages
  dnf:
    autoremove: yes
  when: ansible_os_family == "RedHat"

- name: Install dnf Plugins
  dnf:
    name: "{{ item  }}"
    state: present
  loop: "{{ dnf_plugins  }}"
  when: ansible_os_family == "RedHat"

