---
- name: Verify Docker Installation
  command:  docker --version
  register: docker_version

- name: Verify Docker-Compose Installation
  command:  docker compose version
  register: docker_compose_version

- name: Print Docker Version
  debug:
      msg: "Docker Version is => {{ docker_version.stdout  }}"

- name: Print Docker-compose Version
  debug:
      msg: "Docker Version is => {{ docker_compose_version.stdout  }}"


