---
- name: Use Strategy
  hosts: stra
  become: true
  gather_facts: no
  serial: "100%"
  strategy: free
  tasks:
    - become_user:  "{{ansible_user}}"
      shell:  bash -c "whoami"
      register: test

    - command:  python3 -m http.server 8272
      when: inventory_hostname == "ns1"

    - debug:
        msg:  "{{test.stdout_lines}}"
