---
- name: Diffrent Between Loop & With_items
  hosts:  webserver
  vars_files:
    - "vars.yaml"
  become: true
  tasks:
    - name: Debug Nested List
      debug:
        msg:  "{{ item }}"
      loop: '{{ ["test", ["two", "tests"]] }}' # You Can Pip it to ' | flatten(1,2) ' To Break Items In List

    - name: Debug Nested List
      debug:
        msg:  "{{ item }}"
      with_items: ["test", ["two", "tests"]]

    
