---
- name: This Is First File Of Playbook
  hosts:  kuber
  tasks:
    - name: Print Hello Ansible
      debug:
        msg:  "Hello Ansible"

    - name: "Get Hostname"
      shell:  hostname
      register: output

    - name: Print Hello Ansible
      debug:
         var:  output.stdout_lines


    - name: Exit ansible
      fail:
        msg:  "Exited :)"
