---
- name: This Is First File Of Playbook
  hosts:  kuber
  tasks:
    - name: Print Hello Ansible
      debug:
        msg:  "Hello Ansible"

#    - name: "Get Hostname with shell"
#      shell:  hostname
#      register: output
          
    - name: "Get Hostname with command"
      command:  hostname
      register: output

    - name: Print Variable Value
      debug:
         var:  output.stdout_lines


    - name: Exit ansible
      fail:
        msg:  "Exited :)"
