---
- name: Docker Installation Task ( Rocky Linux )
  hosts:  docker
  become: yes
  vars_files:
    - "vars.yaml"
  tasks:
    - name: Update The Target Server
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Remove The Old Packages For Docker If Exist
      dnf:
        name: "{{ item  }}"
        state:  absent
      loop: "{{ remove_pkg }}"
      when: ansible_os_family == "RedHat"

    - name: Remove Unnecessary Packages
      dnf:
        autoremove: yes
      when: ansible_os_family == "RedHat"

